-- ----------------------------
-- Table structure for PT_AUTHEN_LOG
-- ----------------------------
CREATE TABLE PT_LAYOUT ( 
	TEMPLATEID VARCHAR2(50), 
	SETTING CLOB, PK_LAYOUT VARCHAR2(22) NOT NULL, 
	ID VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100) NOT NULL, 
	CTIME DATE NOT NULL, 
	PARENTID VARCHAR2(50), 
	USERID VARCHAR2(50), 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	ISDEFAULT CHAR(1), 
	MODIFYTIME DATE, 
	ISENABLE CHAR(1), 
	RND VARCHAR2(30), 
	WLEVEL CHAR(1),
	TS DATE, 
	DR INTEGER, 
	PRIMARY KEY (PK_LAYOUT) 
);
-- ----------------------------
-- Table structure for PT_LAYOUT_TEMPLATE
-- ----------------------------
CREATE TABLE PT_LAYOUT_TEMPLATE ( 
	ID VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100) NOT NULL, 
	TPL CLOB NOT NULL, 
	PK_LAYOUT_TEMPLATE VARCHAR2(22) NOT NULL, 
	I18N VARCHAR2(100), 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	TS DATE, 
	DR INTEGER, 
	PRIMARY KEY (PK_LAYOUT_TEMPLATE) 
);
-- ----------------------------
-- Table structure for PT_WIDGET
-- ----------------------------
CREATE TABLE PT_WIDGET ( 
	ID VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100) NOT NULL, 
	DESCR VARCHAR2(300), 
	CATEGORY VARCHAR2(50) NOT NULL, 
	WTYPE VARCHAR2(50) NOT NULL, 
	URL VARCHAR2(300) NOT NULL, 
	PK_WIDGET VARCHAR2(22) NOT NULL, 
	ISENABLE CHAR(1), 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	CTIME DATE, 
	CNF CLOB, 
	MODIFYTIME DATE, 
	SETTING CLOB,
	TS DATE, 
	DR INTEGER, 
	WLEVEL CHAR(1),
	TAG VARCHAR2(30), 
	PRIMARY KEY (PK_WIDGET) 
);
-- ----------------------------
-- Table structure for PT_WIDGET_CATEGORY
-- ----------------------------
CREATE TABLE PT_WIDGET_CATEGORY ( 
	PK_CATEGORY VARCHAR2(22) NOT NULL, 
	ID VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100) NOT NULL, 
	I18N VARCHAR2(100), 
	ISENABLE CHAR(1), 
	SORT INTEGER, 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	TS DATE, 
	DR INTEGER, 
	PRIMARY KEY (PK_CATEGORY) 
);
-- ----------------------------
-- Table structure for PT_WIDGET_PREFERENCE
-- ----------------------------
CREATE TABLE PT_WIDGET_PREFERENCE (
	WIDGETID VARCHAR2(50) NOT NULL, 
	VIEWID VARCHAR2(50) NOT NULL, 
	ID VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100), 
	VALUE VARCHAR2(100), 
	CTIME DATE, 
	PK_WIDGET_PREFERENCE VARCHAR2(22) NOT NULL, 
	USERID VARCHAR2(50), 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	TS DATE, 
	DR INTEGER,
	WSTATUS INTEGER,
	PRIMARY KEY (PK_WIDGET_PREFERENCE) 
);
-- ----------------------------
-- Table structure for PT_THEME
-- ----------------------------
CREATE TABLE PT_THEME ( 
	ID VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100) NOT NULL, 
	ISDEFAULT CHAR(1), 
	CTIME DATE NOT NULL, 
	PK_THEME VARCHAR2(22) NOT NULL, 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	TS DATE, 
	DR INTEGER, 
	PRIMARY KEY (PK_THEME) 
);
-- ----------------------------
-- Table structure for PT_THEME_PREFERENCE
-- ----------------------------
CREATE TABLE PT_THEME_PREFERENCE ( 
	USERID VARCHAR2(50) NOT NULL, 
	THEMEID VARCHAR2(50) NOT NULL, 
	PK_THEME_PREFERENCE VARCHAR2(22) NOT NULL, 
	SYSTEM VARCHAR2(50), 
	TENANT VARCHAR2(50), 
	TS DATE, 
	DR INTEGER, 
	PRIMARY KEY (PK_THEME_PREFERENCE) 
);
-- ----------------------------
-- Table structure for PT_MORE_MENU
-- ----------------------------
CREATE TABLE PT_MORE_MENU ( 
	CODE VARCHAR2(50) NOT NULL, 
	NAME VARCHAR2(100) NOT NULL, 
	URL VARCHAR2(300) NOT NULL, 
	URL_TYPE  VARCHAR2(10) NOT NULL,
	ICON VARCHAR2(50),
	SORT INTEGER,
	TAG VARCHAR2(50) ,
	PK_MORE_MENU VARCHAR2(50) NOT NULL, 
	ISENABLE CHAR(1),
	SYSTEM VARCHAR2(50),
	TENANT VARCHAR2(50), 
	TS DATE, 
	DR INTEGER, 
	PRIMARY KEY (PK_MORE_MENU) 
);
