-- MYSQL
CREATE TABLE example_instit (
  institid CHAR(36) PRIMARY KEY,
  instit_code VARCHAR(200) NOT NULL,
  instit_name VARCHAR(200) NOT NULL,
  short_name VARCHAR(50) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  instit_type VARCHAR(10) DEFAULT NULL,
  parent_id VARCHAR(36) DEFAULT NULL,
  creator VARCHAR(20) DEFAULT NULL,
  creationtime DATE DEFAULT NULL,
  ts DATE DEFAULT NULL,
  dr INT(11) DEFAULT '0'
);


CREATE TABLE example_record (
  id VARCHAR(36) PRIMARY KEY,
  CODE VARCHAR(50) DEFAULT NULL,
  NAME VARCHAR(50) DEFAULT NULL,
  sys VARCHAR(50) DEFAULT NULL,
  creator VARCHAR(50) DEFAULT NULL,
  create_time VARCHAR(50) DEFAULT NULL,
  remark VARCHAR(50) DEFAULT NULL
);



CREATE TABLE example_telbook (
  id CHAR(36) PRIMARY KEY,
  peocode VARCHAR(100) NOT NULL,
  peoname VARCHAR(50) NOT NULL,
  sex VARCHAR(50) DEFAULT NULL,
  worktel VARCHAR(100) DEFAULT NULL,
  office VARCHAR(100) DEFAULT NULL,
  tel VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  countryzone VARCHAR(36) DEFAULT NULL,
  institid CHAR(36) DEFAULT NULL,
  institname CHAR(50) DEFAULT NULL,
  ts DATE DEFAULT NULL,
  dr INT(11) DEFAULT '0'
);